### ISSUE TITLE
missing vaultaddr parameter

### ISSUE THREAD

**Issue by inodes** [samrocketman/docker-compose-ha-consul-vault-ui#1]
Currently running the docker-compose verbatim on an EC2 instance for testing purposes.
After successful unseal, attempting to connect to Vault using the EC2's private ip address (security groups are not an issue here where 10.201.144.8 is the private ip of the EC2 instance).

Getting error:

```
$ vault login -address=http://10.201.144.8:8000
Token (will be hidden):
Error authenticating: error looking up token: Error making API request.

URL: GET http://10.201.144.8:8000/v1/auth/token/lookup-self
Code: 400. Raw Message:

missing vaultaddr parameter
```

The same is noted from the browser on http://10.201.144.8:8000/v1/auth/token/lookup-self of course

**Comment by samrocketman** [comment]
The docker-compose example isn’t designed to be run in production.  It’s meant to serve as an exmple.  Each service in the docker-compose.yml should be in its own cluster in practice.

**Comment by samrocketman** [comment]
I guess to be a little more clear I just mean this project is meant for someone to run on their laptop and try out Consul and Vault in a HA configuration.  As well as play with Consul DNS.
