### ISSUE TITLE
Script de lancement en défaut

### ISSUE THREAD

**Issue by GVA-Guillaume** [samrocketman/docker-compose-ha-consul-vault-ui#11]
Bonjour c'est un projet TRES COMPLET, j'ai essayé le script avec ou sans les trois instances vaults, mais le script est en défaut, je regarderai tout ça plus tard, je monte actuellement un projet sur la transparence et la confidentialité, j'espère que tout va bien, des compétences comme la tienne pourrait tout à fait être en adéquation avec les ambitions de cette activité pour tous.

**Comment by samrocketman** [comment]
Bonjour, j'ai utilisé google traduction.

Je suis content que cela vous aide. Cela fait longtemps que je n'ai pas commencé ce projet donc je vais l'essayer. Je vais m'assurer qu'il fonctionne de manière fiable.
