### ISSUE TITLE
Add support for TLS connection for Consul and Vault

### ISSUE THREAD

**Issue by lrabiet** [samrocketman/docker-compose-ha-consul-vault-ui#3]
No cert and Key in the config. It would be nice to get a tls connection everywhere.

**Comment by samrocketman** [comment]
This probably wouldn’t be hard to do using my custom certificate authority https://github.com/samrocketman/my_internal_ca.

But it would add extra steps to setting up consul and vault locally which is outside the scope of this demo for learning vault and consul on your laptop.
