### ISSUE TITLE
if we don't want to use dnsmasq

### ISSUE THREAD

**Issue by killermoon** [samrocketman/docker-compose-ha-consul-vault-ui#4]
Nice but can we do the same without dnsmasq  and by exposing the current vault service available ? Do you have any idea how to change it  ?

**Comment by samrocketman** [comment]
dnsmasq is necessary because consul DNS.  You could use something like iptables to redirect the port but that’s outside the scope of this demo for me.  You’re welcome to modify it for your needs but it works well enough for me to learn consul, vault, and different features of each.
