### ISSUE TITLE
Vault Swarm IP issue

### ISSUE THREAD

**Issue by ericbram** [samrocketman/docker-compose-ha-consul-vault-ui#6]
First of all, thank you so much for this repo.  I found the Vault documentation to be severely lacking when trying to understand how to deal with Vault in a Swarm scenario.  

I borrowed [this](https://github.com/samrocketman/docker-compose-ha-consul-vault-ui/blob/master/docker-compose.yml#L129-L131) section of code which was the major breakthrough to get it working for me, but after much debugging, found that the "default" network was not the correct network to be connecting to.  I'm not sure exactly why, but my default was pointing to eth2 and it needed to be eth0.  After modifying the script to get eth0's IP, clustering the Vault containers worked beautifully.  

Mostly putting this here for anyone else to find as well.

**Comment by samrocketman** [comment]
Thanks for reporting.  I haven't used swarm beyond personal play.

**Comment by samrocketman** [comment]
I assume this is the original link based on the description.  Added git hash so that the link stays reliable https://github.com/samrocketman/docker-compose-ha-consul-vault-ui/blob/205922eb923074ac7347136b2e476d8dd37937f1/docker-compose.yml#L130-L132
