### ISSUE TITLE
Supported OS?

### ISSUE THREAD

**Issue by M1kep** [samrocketman/docker-compose-ha-consul-vault-ui#7]
Attempting to use this on MacOS but running into quite a few issues with file encoding and commands etc. Some examples:

- sh: ./scripts/consul-agent.sh: bad interpreter: /bin/sh^M: no such file or directory
-  - Running with sh directly appears to work.(Unsure as I wasn't able to access UI, but it does appear to have brought up the needed dockers instances when running docker-compose up)
- `: command not founde-vault.sh: line 2:
: invalid optionlize-vault.sh: line 3: set: -
set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]`
- - Not too sure about this one

Not sure if this is a me issue, or just has not been tested on MacOS

Either way, looking forward to testing this on a Linux box if needed

**Comment by samrocketman** [comment]
You can't run the agent from Mac OS but you can bootstrap it.  See the README: https://github.com/samrocketman/docker-compose-ha-consul-vault-ui#start-the-cluster
